import type { Grant } from "./types"

export const sampleGrants: Grant[] = [
  {
    id: "grant-1",
    title: "STEM Innovation Grant for Educators",
    description:
      "Funding for innovative STEM projects that engage students in hands-on learning experiences. Projects should demonstrate creative approaches to teaching science, technology, engineering, or mathematics concepts.",
    amount: 5000,
    deadline: "April 15, 2025",
    category: "STEM",
    eligibility: ["K-12 Teachers", "Public Schools", "Charter Schools"],
    fundingSource: "National Science Foundation",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-2",
    title: "Arts Integration in the Classroom",
    description:
      "Support for teachers integrating arts into core curriculum subjects to enhance student learning. Successful projects will demonstrate measurable academic outcomes through arts-based teaching methods.",
    amount: 3500,
    deadline: "May 30, 2025",
    category: "Arts",
    eligibility: ["Elementary Teachers", "Middle School Teachers", "Title I Schools"],
    fundingSource: "National Endowment for the Arts",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-3",
    title: "Digital Literacy Initiative",
    description:
      "Funding to support digital literacy programs and technology integration in underserved schools. Programs should address the digital divide and provide students with essential technology skills for future success.",
    amount: 7500,
    deadline: "June 15, 2025",
    category: "Technology",
    eligibility: ["K-12 Schools", "Title I Schools", "Rural Schools"],
    fundingSource: "Department of Education",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-4",
    title: "Teacher Professional Development Grant",
    description:
      "Support for teachers seeking advanced certifications or specialized training in their field. Funds can be used for course fees, materials, and substitute teacher coverage during training periods.",
    amount: 2500,
    deadline: "July 1, 2025",
    category: "Professional Development",
    eligibility: ["K-12 Teachers", "Public Schools", "Private Schools"],
    fundingSource: "Education Foundation of America",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-5",
    title: "Inclusive Classroom Resources Grant",
    description:
      "Funding for resources and materials to support diverse learners and create inclusive classrooms. Grants support the purchase of specialized equipment, curriculum materials, and assistive technologies.",
    amount: 4000,
    deadline: "August 15, 2025",
    category: "Special Education",
    eligibility: ["Special Education Teachers", "K-12 Schools", "Inclusive Classrooms"],
    fundingSource: "Special Education Foundation",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-6",
    title: "Early Literacy Program Support",
    description:
      "Funding to enhance early literacy programs and reading initiatives for young learners. Programs should focus on foundational reading skills and creating a culture of reading in early childhood settings.",
    amount: 6000,
    deadline: "September 1, 2025",
    category: "Literacy",
    eligibility: ["Elementary Schools", "Pre-K Programs", "Title I Schools"],
    fundingSource: "Reading Is Fundamental",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-7",
    title: "Environmental Education Project Grant",
    description:
      "Support for projects that engage students in environmental science and sustainability initiatives. Projects should include hands-on learning experiences and community engagement components.",
    amount: 5500,
    deadline: "October 15, 2025",
    category: "STEM",
    eligibility: ["K-12 Teachers", "Public Schools", "Private Schools"],
    fundingSource: "Environmental Protection Agency",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-8",
    title: "Classroom Technology Upgrade Grant",
    description:
      "Funding for classroom technology upgrades including hardware, software, and digital learning tools. Grants can support the purchase of computers, tablets, interactive displays, and educational software.",
    amount: 10000,
    deadline: "November 30, 2025",
    category: "Technology",
    eligibility: ["K-12 Schools", "Public Schools", "Charter Schools"],
    fundingSource: "Technology for Education Foundation",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-9",
    title: "Multicultural Literature Collection Grant",
    description:
      "Support for expanding classroom and school libraries with diverse and multicultural literature. Funds can be used to purchase books, e-books, and multimedia resources that reflect diverse perspectives and experiences.",
    amount: 3000,
    deadline: "December 15, 2025",
    category: "Literacy",
    eligibility: ["K-12 Schools", "School Librarians", "Language Arts Teachers"],
    fundingSource: "Diverse Books Initiative",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-10",
    title: "Social-Emotional Learning Implementation Grant",
    description:
      "Funding to support the implementation of social-emotional learning programs in schools. Grants can cover curriculum materials, professional development, and program evaluation.",
    amount: 8000,
    deadline: "January 15, 2025",
    category: "Mental Health",
    eligibility: ["K-12 Schools", "School Counselors", "School Psychologists"],
    fundingSource: "Mental Health America",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-11",
    title: "Outdoor Learning Space Development",
    description:
      "Support for creating or enhancing outdoor learning environments on school grounds. Projects may include gardens, outdoor classrooms, nature trails, or other spaces that facilitate learning in natural settings.",
    amount: 12000,
    deadline: "February 28, 2025",
    category: "Facilities",
    eligibility: ["K-12 Schools", "Early Childhood Centers", "Public Schools"],
    fundingSource: "Outdoor Education Foundation",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-12",
    title: "Robotics and Coding Program Grant",
    description:
      "Funding for establishing or expanding robotics and coding programs in schools. Grants can support equipment purchases, competition fees, and instructor training.",
    amount: 7500,
    deadline: "March 15, 2025",
    category: "STEM",
    eligibility: ["K-12 Schools", "STEM Teachers", "After-School Programs"],
    fundingSource: "Computer Science Education Coalition",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-13",
    title: "Music Education Enhancement Grant",
    description:
      "Support for enhancing music education programs through instrument purchases, sheet music, technology, and specialized instruction. Priority given to programs serving underrepresented students.",
    amount: 6500,
    deadline: "April 30, 2025",
    category: "Arts",
    eligibility: ["K-12 Schools", "Music Teachers", "Title I Schools"],
    fundingSource: "National Association for Music Education",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-14",
    title: "Bilingual Education Resources Grant",
    description:
      "Funding for resources and materials to support bilingual and dual-language education programs. Grants can support curriculum development, classroom materials, and teacher training.",
    amount: 5000,
    deadline: "May 15, 2025",
    category: "Language",
    eligibility: ["K-12 Schools", "ESL Teachers", "Dual Language Programs"],
    fundingSource: "Multilingual Education Alliance",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-15",
    title: "Physical Education Equipment Grant",
    description:
      "Support for purchasing physical education equipment and implementing innovative PE programs that promote lifelong fitness and wellness among students.",
    amount: 4500,
    deadline: "June 30, 2025",
    category: "Health",
    eligibility: ["K-12 Schools", "Physical Education Teachers", "School Districts"],
    fundingSource: "Physical Education Foundation",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-16",
    title: "School Garden and Nutrition Education Grant",
    description:
      "Funding for establishing or enhancing school gardens and implementing nutrition education programs. Projects should connect garden activities to curriculum and promote healthy eating habits.",
    amount: 3500,
    deadline: "July 15, 2025",
    category: "Health",
    eligibility: ["K-12 Schools", "Science Teachers", "Health Educators"],
    fundingSource: "Healthy Schools Coalition",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-17",
    title: "Career and Technical Education Equipment Grant",
    description:
      "Support for purchasing equipment and materials for career and technical education programs. Funds can be used for industry-standard tools, technology, and specialized equipment.",
    amount: 15000,
    deadline: "August 31, 2025",
    category: "Vocational",
    eligibility: ["High Schools", "Technical Schools", "CTE Programs"],
    fundingSource: "Career Readiness Foundation",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-18",
    title: "School Library Modernization Grant",
    description:
      "Funding to transform traditional school libraries into modern learning commons with flexible spaces, technology integration, and updated collections.",
    amount: 20000,
    deadline: "September 30, 2025",
    category: "Facilities",
    eligibility: ["K-12 Schools", "School Librarians", "Media Specialists"],
    fundingSource: "Modern Library Initiative",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-19",
    title: "STEAM Project-Based Learning Grant",
    description:
      "Support for implementing project-based learning initiatives that integrate science, technology, engineering, arts, and mathematics (STEAM). Projects should be interdisciplinary and student-centered.",
    amount: 8500,
    deadline: "October 31, 2025",
    category: "STEM",
    eligibility: ["K-12 Teachers", "STEAM Coordinators", "Public Schools"],
    fundingSource: "STEAM Education Alliance",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-20",
    title: "School Safety and Security Enhancement Grant",
    description:
      "Funding for implementing or upgrading school safety and security measures. Grants can support technology, training, and facility modifications to create safer learning environments.",
    amount: 25000,
    deadline: "November 15, 2025",
    category: "Safety",
    eligibility: ["K-12 Schools", "School Districts", "School Security Officers"],
    fundingSource: "Safe Schools Initiative",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-21",
    title: "Virtual Reality in Education Grant",
    description:
      "Support for implementing virtual reality technology in classrooms to enhance learning experiences. Funds can be used for VR headsets, software, and teacher training.",
    amount: 12000,
    deadline: "December 31, 2025",
    category: "Technology",
    eligibility: ["K-12 Schools", "Technology Coordinators", "STEM Teachers"],
    fundingSource: "Educational Technology Consortium",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-22",
    title: "Gifted and Talented Program Enhancement",
    description:
      "Funding to enhance programs and services for gifted and talented students. Grants can support curriculum development, enrichment activities, and teacher professional development.",
    amount: 6000,
    deadline: "January 31, 2026",
    category: "Special Education",
    eligibility: ["K-12 Schools", "Gifted Education Specialists", "School Districts"],
    fundingSource: "Gifted Education Foundation",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-23",
    title: "School Counseling Program Support Grant",
    description:
      "Support for enhancing school counseling programs and services. Funds can be used for resources, professional development, and innovative counseling initiatives.",
    amount: 5500,
    deadline: "February 15, 2026",
    category: "Mental Health",
    eligibility: ["K-12 Schools", "School Counselors", "Student Support Teams"],
    fundingSource: "School Counseling Association",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-24",
    title: "Innovative Math Curriculum Implementation",
    description:
      "Funding for implementing innovative mathematics curriculum and teaching approaches. Grants support materials, professional development, and program evaluation.",
    amount: 7000,
    deadline: "March 31, 2026",
    category: "STEM",
    eligibility: ["K-12 Schools", "Math Teachers", "Curriculum Specialists"],
    fundingSource: "Mathematics Education Trust",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-25",
    title: "School-Community Partnership Grant",
    description:
      "Support for developing and strengthening partnerships between schools and community organizations. Projects should demonstrate mutual benefits and sustainable collaboration.",
    amount: 10000,
    deadline: "April 30, 2026",
    category: "Community",
    eligibility: ["K-12 Schools", "Community Organizations", "School Districts"],
    fundingSource: "Community Engagement Foundation",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-26",
    title: "Classroom Furniture Modernization Grant",
    description:
      "Funding to update classroom furniture with flexible, ergonomic options that support various learning styles and teaching approaches.",
    amount: 15000,
    deadline: "May 15, 2026",
    category: "Facilities",
    eligibility: ["K-12 Schools", "School Administrators", "Classroom Teachers"],
    fundingSource: "Modern Learning Environments Initiative",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-27",
    title: "Artificial Intelligence in Education Grant",
    description:
      "Support for implementing artificial intelligence tools and curriculum in K-12 education. Projects should focus on responsible AI use and preparing students for an AI-integrated future.",
    amount: 18000,
    deadline: "June 30, 2026",
    category: "Technology",
    eligibility: ["K-12 Schools", "Technology Coordinators", "Computer Science Teachers"],
    fundingSource: "AI Education Foundation",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-28",
    title: "Performing Arts Program Enhancement Grant",
    description:
      "Funding to enhance school performing arts programs including theater, dance, and music. Grants can support equipment, materials, productions, and specialized instruction.",
    amount: 9000,
    deadline: "July 31, 2026",
    category: "Arts",
    eligibility: ["K-12 Schools", "Performing Arts Teachers", "After-School Programs"],
    fundingSource: "Performing Arts Education Alliance",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-29",
    title: "Financial Literacy Education Grant",
    description:
      "Support for implementing financial literacy education programs in schools. Funds can be used for curriculum materials, technology tools, and teacher training.",
    amount: 5000,
    deadline: "August 15, 2026",
    category: "Life Skills",
    eligibility: ["Middle Schools", "High Schools", "Economics Teachers"],
    fundingSource: "Financial Education Initiative",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-30",
    title: "Innovative Science Lab Equipment Grant",
    description:
      "Funding for purchasing modern science laboratory equipment and supplies. Grants support hands-on, inquiry-based science education across grade levels.",
    amount: 12500,
    deadline: "September 30, 2026",
    category: "STEM",
    eligibility: ["K-12 Schools", "Science Teachers", "STEM Coordinators"],
    fundingSource: "Science Education Foundation",
    applicationLink: "https://example.com/apply",
  },
]