import type { Grant } from "./types"

export const sampleGrants: Grant[] = [
  {
    id: "grant-1",
    title: "STEM Innovation Grant for Educators",
    description: "Funding for innovative STEM projects that engage students in hands-on learning experiences.",
    amount: 5000,
    deadline: "April 15, 2024",
    category: "STEM",
    eligibility: ["K-12 Teachers", "Public Schools", "Charter Schools"],
    fundingSource: "National Science Foundation",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-2",
    title: "Arts Integration in the Classroom",
    description: "Support for teachers integrating arts into core curriculum subjects to enhance student learning.",
    amount: 3500,
    deadline: "May 30, 2024",
    category: "Arts",
    eligibility: ["Elementary Teachers", "Middle School Teachers", "Title I Schools"],
    fundingSource: "National Endowment for the Arts",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-3",
    title: "Digital Literacy Initiative",
    description: "Funding to support digital literacy programs and technology integration in underserved schools.",
    amount: 7500,
    deadline: "June 15, 2024",
    category: "Technology",
    eligibility: ["K-12 Schools", "Title I Schools", "Rural Schools"],
    fundingSource: "Department of Education",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-4",
    title: "Teacher Professional Development Grant",
    description: "Support for teachers seeking advanced certifications or specialized training in their field.",
    amount: 2500,
    deadline: "July 1, 2024",
    category: "Professional Development",
    eligibility: ["K-12 Teachers", "Public Schools", "Private Schools"],
    fundingSource: "Education Foundation of America",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-5",
    title: "Inclusive Classroom Resources Grant",
    description: "Funding for resources and materials to support diverse learners and create inclusive classrooms.",
    amount: 4000,
    deadline: "August 15, 2024",
    category: "Special Education",
    eligibility: ["Special Education Teachers", "K-12 Schools", "Inclusive Classrooms"],
    fundingSource: "Special Education Foundation",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-6",
    title: "Early Literacy Program Support",
    description: "Funding to enhance early literacy programs and reading initiatives for young learners.",
    amount: 6000,
    deadline: "September 1, 2024",
    category: "Literacy",
    eligibility: ["Elementary Schools", "Pre-K Programs", "Title I Schools"],
    fundingSource: "Reading Is Fundamental",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-7",
    title: "Environmental Education Project Grant",
    description: "Support for projects that engage students in environmental science and sustainability initiatives.",
    amount: 5500,
    deadline: "October 15, 2024",
    category: "STEM",
    eligibility: ["K-12 Teachers", "Public Schools", "Private Schools"],
    fundingSource: "Environmental Protection Agency",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-8",
    title: "Classroom Technology Upgrade Grant",
    description: "Funding for classroom technology upgrades including hardware, software, and digital learning tools.",
    amount: 10000,
    deadline: "November 30, 2024",
    category: "Technology",
    eligibility: ["K-12 Schools", "Public Schools", "Charter Schools"],
    fundingSource: "Technology for Education Foundation",
    applicationLink: "https://example.com/apply",
  },
  {
    id: "grant-9",
    title: "Multicultural Literature Collection Grant",
    description: "Support for expanding classroom and school libraries with diverse and multicultural literature.",
    amount: 3000,
    deadline: "December 15, 2024",
    category: "Literacy",
    eligibility: ["K-12 Schools", "School Librarians", "Language Arts Teachers"],
    fundingSource: "Diverse Books Initiative",
    applicationLink: "https://example.com/apply",
  },
]

